# Generated by Django 4.2.3 on 2023-07-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=250)),
                ('m_img', models.ImageField(upload_to='team')),
                ('m_desc', models.TextField()),
            ],
        ),
    ]
